### ISSUE TITLE
Check dark mode contrast

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#112]
Just a note to check we are happy with the dark mode colours as a couple of reviewers have mentioned difficulties with the contrast when using dark mode. Specifically, some people are having trouble focussing on the text because the borders are very bright, others mentioned that the buttons on the homepage are hard to distinguish in dark mode:

![image](https://user-images.githubusercontent.com/33655003/205261132-dc05ca33-e425-40ae-96ba-d930e19ae69c.png)

Note that other reviewers did not agree with this, so this issue is just to prompt us to consider it and make a decision.

**Comment by nloureiro** [comment]
to fix I propose to make the button background a bit darker

#01100D
![Screen Shot 2022-12-02 11 43 57 AM](https://user-images.githubusercontent.com/1120748/205285500-578f0d8b-b1ef-4b43-b0bd-9d74cce9a502.png)


![Screen Shot 2022-12-02 11 44 52 AM](https://user-images.githubusercontent.com/1120748/205285697-85f46a6d-0cca-417e-8703-71abd20fb6d6.png)

**Comment by wackerow** [comment]
I think that helps on the dark mode side, but we also have a low contrast ratio on light mode with the current background colors we use. 
<img width="1795" alt="image" src="https://user-images.githubusercontent.com/54227730/206076743-1488ad4a-75cc-4a4a-9862-6402700bf14a.png">
<img width="400" alt="image" src="https://user-images.githubusercontent.com/54227730/206077035-7584715b-3f65-40e0-8789-0a4b02c817bf.png">
https://dequeuniversity.com/rules/axe/4.4/color-contrast

We may also want to consider addressing this

**Comment by wackerow** [comment]
If we use `green.700` (#08715C) instead of `green.600` for `primary` in light mode, this resolves the browser warnings I'm getting about the contrast ratio.

`primary: { _light: 'green.700', _dark: 'green.200' },`
instead of `primary: { _light: 'green.600', _dark: 'green.200' },`

<img width="1040" alt="image" src="https://user-images.githubusercontent.com/54227730/206080042-2a8f5207-918e-4fe4-bbc5-d8b6ea6b7f8b.png">

@nloureiro Curious your take

**Comment by nloureiro** [comment]
> If we use `green.700` (#08715C) instead of `green.600` for `primary` in light mode, this resolves the browser warnings I'm getting about the contrast ratio.
> 
> `primary: { _light: 'green.700', _dark: 'green.200' },` instead of `primary: { _light: 'green.600', _dark: 'green.200' },`
> 
> <img alt="image" width="1040" src="https://user-images.githubusercontent.com/54227730/206080042-2a8f5207-918e-4fe4-bbc5-d8b6ea6b7f8b.png">
> 
> @nloureiro Curious your take



I've tested Figma, and yes, your proposal to change the primary to #green.700 is the best option.

Made a Figma with the testing.
https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=2601%3A20493&t=IM0cQlwLjB4YYIVG-1

![Screen Shot 2022-12-07 10 00 23 AM](https://user-images.githubusercontent.com/1120748/206158892-e4f1cfe4-983a-4971-bb6b-e1fc648ed20f.png)
