### ISSUE TITLE
[MARKUP BUG] buttons on the homepage have a double <a>

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#113]
all the buttons on the homepage have a <a><a> [button content] </a></a>

Why the double link?
![Screen Shot 2022-12-02 11 05 01 AM](https://user-images.githubusercontent.com/1120748/205279217-63daba66-c9e2-4ec5-9ab6-afc42b3455e4.png)

**Comment by nhsz** [comment]
This is not a bug, [is the next/link component wrapping Chakra's link](https://jools.dev/using-nextjs-link-with-chakra-ui-link).

**Comment by nloureiro** [comment]
Ok, I see the point, but the markup is ugly and unnecessary to some extent. ::sad::
