### ISSUE TITLE
[DESING UPDATE] increase the font size of H1

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#114]
H1 it's a bitt too small.

desktop > 2.125rem >>> to >>> 2.875rem/46px

Mobile >  font-size: 1.875rem;  >>> to >>>  font-size: 2.175rem;

screenshots with the new font size 
![Screen Shot 2022-12-02 12 00 06 AM](https://user-images.githubusercontent.com/1120748/205288287-70a7d655-6d34-4754-ba43-7bed6f09d22d.png)
![Screen Shot 2022-12-02 11 59 46 AM](https://user-images.githubusercontent.com/1120748/205288293-15c5c1a2-1443-46a9-b877-bce980aa89ae.png)
![Screen Shot 2022-12-02 11 55 48 AM](https://user-images.githubusercontent.com/1120748/205288295-523e13eb-2058-40d9-8fa9-4f05b0401621.png)

**Comment by nhsz** [comment]
@nloureiro this is just for docs page?

**Comment by nloureiro** [comment]
> @nloureiro this is just for docs page?

no, to all the pages

**Comment by corwintines** [comment]
@nhsz added a fix for this
