### ISSUE TITLE
[DESIGN BUG] Some MD pages causing horizontal overflow

### ISSUE THREAD

**Issue by wackerow** [ethereum/geth-website#119]
Page is overflowing on mobile:

<img src="https://user-images.githubusercontent.com/54227730/205469653-469552fa-2fc5-4f3d-9309-475e9152067a.png" height="500px" width="auto" />

https://melodious-puffpuff-8e1109.netlify.app/docs/developers/evm-tracing/custom-tracer

Which causes an even stranger bug if the hamburger menu is then opened:
<img src="https://user-images.githubusercontent.com/54227730/205469677-d7f2ac73-d029-48cc-8f37-871f9aa33eed.png" height="500px" width="auto" />

I haven't come across this on any other pages yet

**Comment by wackerow** [comment]
Seeing it here too: https://melodious-puffpuff-8e1109.netlify.app/docs/fundamentals/command-line-options

**Comment by minimalsm** [comment]
I think this is related to/covered by #92
