### ISSUE TITLE
Footer links: click area does not cover entire button

### ISSUE THREAD

**Issue by wackerow** [ethereum/geth-website#126]
## Issue
Link buttons in the footer change styling when user hovers anywhere in the div, but the actual link is only accessible over the text itself. 

The other similar buttons on the site do no function this way. 

## Clip
https://user-images.githubusercontent.com/54227730/205701129-3326c9d8-e7b7-4f9c-824d-03403d45a5da.mov

## Expected behavior
The entire div should be clickable as a link, not just the  text itself.

**Comment by nhsz** [comment]
Closing as it's already reported on https://github.com/ethereum/geth-website/issues/90
