### ISSUE TITLE
[UX IMPROVEMENT] empty tabs on the download table need a default message

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#132]
to avoid having empty tabs on the download realises tabs, there  should be a default message for empty tabs

"No builds found"

and should have a min-height of 20rem/320px

For the text use the h4 style

![Screen Shot 2022-12-06 02 29 44 PM](https://user-images.githubusercontent.com/1120748/205939006-9fdfe4b3-030c-4a56-bdc9-9f0da785830f.png)

**Comment by nhsz** [comment]
@nloureiro we have removed the text of "Showing n releases..." from the tables. Also I think in case of no results, the show older releases button should be hidden.
