### ISSUE TITLE
code snippets with language == "terminal" not parsing line breaks

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#156]
Code snippets with language specified as `terminal` are not rendering correctly. Instead of correctly parsing line breaks the code is rendered as a continuous block of characters. e.g.

![image](https://user-images.githubusercontent.com/33655003/207309977-b2851716-fcee-43e9-a2a1-5deca5273a35.png)

**Comment by nhsz** [comment]
Fixed by #146
