### ISSUE TITLE
Update table hover color

### ISSUE THREAD

**Issue by corwintines** [ethereum/geth-website#16]
When design system is updated for table row hover color, update this in the codebase

**Comment by nloureiro** [comment]
Let's use the button background color

![Screen Shot 2022-11-17 04 42 03 PM](https://user-images.githubusercontent.com/1120748/202505694-90ec51d1-20b4-46a1-a662-f47ebcc0147d.png)
![Screen Shot 2022-11-17 04 41 53 PM](https://user-images.githubusercontent.com/1120748/202505710-49b6a196-84de-42c6-b742-b5df52f270e0.png)

**Comment by nhsz** [comment]
Closing as this is fixed
