### ISSUE TITLE
[DESIGN BUG] spacing of the boxes should be 2rem in desktop

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#161]
spacing of the boxes should be 2rem in desktop

![Screen Shot 2022-12-14 03 04 19 PM](https://user-images.githubusercontent.com/1120748/207631605-141ee36a-9cff-413a-9b33-814dcaebfdba.png)

**Comment by nhsz** [comment]
@nloureiro spacing with header/footer keeps the same (1rem)?
