### ISSUE TITLE
[UX SUGGESTION] Active section should be expanded on docs page load

### ISSUE THREAD

**Issue by wackerow** [ethereum/geth-website#164]
## Issue
Recently the left navigation of the docs pages was changes to be fully collapsed. I agree that collapsing helps overall, but we should at least have the section that the user is active in expanded. The `/docs` page is debatable, but I think having the "Getting started" section open when a user lands on that page would be most appropriate.

## Screenshot
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/54227730/207753982-2714a106-89b0-4b87-99c9-31fcbd2d19ac.png">
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/54227730/207754418-fd918c05-d934-4dd9-bce3-7b1db74cc71f.png">

This is what currently loads on the left anytime any docs page is loaded from a direct link or with a refresh of page.

## Proposed solution
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/54227730/207754253-84bd6c82-6497-4471-a78a-12b8f596aa23.png">
<img width="1497" alt="image" src="https://user-images.githubusercontent.com/54227730/207754445-bb722ca0-b2e6-48c5-b81e-e04dbb4c7602.png">

Keep the active section option.

**Comment by nhsz** [comment]
@nloureiro @jmcook1186 what do you think

**Comment by wackerow** [comment]
Bringing discussion from Discord, I referenced the DAppNode docs as an example of where this type of behavior is implemented:
https://docs.dappnode.io/user-guide/ui/dashboard ...loads to:
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/54227730/207771678-6148609d-c8b0-4a91-aec2-f60e247362f7.png">

If we want to keep them all closed by default, I would at the very least suggest we have some type of indicator on the menu section that the user is located in. 
cc: @nloureiro @jmcook1186

**Comment by samajammin** [comment]
I agree with this. I think behaviour should follow the same as e.org unless we think there's good reason to change (and if so, I think we should roll out those changes on e.org as well - i.e. we should keep UX consistent).

e.g. opening up this page:
https://ethereum.org/en/developers/docs/nodes-and-clients/node-architecture/

The default behaviour is to expand the side navigation to show the active page.

**Comment by samajammin** [comment]
> https://docs.dappnode.io/user-guide/ui/dashboard ...loads to:

FYI @wackerow this 404s for me

**Comment by wackerow** [comment]
Sorry, https://docs.dappnode.io/user/product-manual/dashboard not sure how that got goofed up, but yeah, just any page in their docs you'll see the default behavior shows you exactly where you're located, and similarly on ethereum.org.

**Comment by samajammin** [comment]
I think this is the e.org implementation here: https://github.com/ethereum/ethereum-org-website/blob/dev/src/components/SideNav.tsx#L91

Perhaps we could mimic this behavior?
