### ISSUE TITLE
Top image in download it's a pixel svg

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#17]
This image is kinda blurry. Being a SVG was not supposed to be.

As far as I could inspect the SVG, looks like pixel image inside SVG.

file: gopher-downloads-front-light.svg

![Screen Shot 2022-10-18 03 24 05 PM](https://user-images.githubusercontent.com/1120748/196458125-8af318c2-a8d0-4dce-9c75-24568a37062b.png)
![Screen Shot 2022-10-18 03 28 48 PM](https://user-images.githubusercontent.com/1120748/196459446-0eca6313-3b40-46b0-bdcf-d8c0adb31b12.png)

**Comment by corwintines** [comment]
I think we can close this out now @nloureiro. @wackerow did a bunch of refactors around this

**Comment by wackerow** [comment]
Yep, that should be taken care of, closing out.

**Comment by wackerow** [comment]
See https://github.com/ethereum/geth-website/pull/31 for implementation of `GopherDownloads.tsx`
