### ISSUE TITLE
[DESIGN UPDATE] increase the line height for the text

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#170]
The line height is now at 1.5 and it's more comfortable to read with a very small increment. 1.5 to 1.6

![Screen Shot 2022-12-15 11 03 38 AM](https://user-images.githubusercontent.com/1120748/207843433-b3f26303-f350-4126-a906-a0b08d0331a8.png)

**Comment by nhsz** [comment]
@nloureiro `1.5` is a [Chakra theme value](https://v1.chakra-ui.com/docs/styled-system/theming/theme?scroll=true#spacing) (0.375rem), could you define the value in rems? There's no `1.6` in the theme

**Comment by nloureiro** [comment]
> @nloureiro `1.5` is a [Chakra theme value](https://v1.chakra-ui.com/docs/styled-system/theming/theme?scroll=true#spacing) (equals to 0.375rem), could you define the value in rems? There's no `1.6` in the theme


@nhsz what is this 1.5 here?
![Screen Shot 2022-12-15 06 30 03 PM](https://user-images.githubusercontent.com/1120748/207939900-1836c6c2-afa4-466a-ba5d-2b006db1083d.png)

**Comment by nhsz** [comment]
@nloureiro oh I see, my bad
