### ISSUE TITLE
where is the footer?

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#18]
As far as I could check preview links, I haven't seen the footer anywhere.

is it on some other branch?

![Screen Shot 2022-10-18 03 33 12 PM](https://user-images.githubusercontent.com/1120748/196460529-498ab1ab-d0e3-481a-a941-fb6a7b69ea09.png)

**Comment by jmcook1186** [comment]
Corwin mentioned dealing with that this week
https://discord.com/channels/420394352083337236/999036134174761100/1031589635161333880

**Comment by corwintines** [comment]
Going to close this out as footer is now implemented
