### ISSUE TITLE
Markdown formatting consistency

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#2]
This issue tracks which pages have been audited for formatting consistency.
The spec for page formatting is [here](https://www.notion.so/efdn/Story-Geth-site-define-markdown-formats-c5d5f312ceac4847b123b0192aa94621)

## Frontmatter for pages

- `title` - title tag for the page (ideally <60 characters)
    - More info on title tags: [https://moz.com/learn/seo/title-tag](https://moz.com/learn/seo/title-tag)
- `description` - meta description of the page (ideally <160 characters)
- More info on meta descriptions: [https://moz.com/learn/seo/meta-description](https://moz.com/learn/seo/meta-description)
        - 
## Internal linking structure
- **Links**
    - Use absolute URIs, e.g.
        - `Return [home](/)`
        - `View the [contribution guidelines](/docs/developers/contributing)`
    - Do NOT use relative URIs, e.g.
        - `Return [home](../)`
        - `View the [contribution guidelines](../../docs/developers/contributing)`
- **Images**
    - Place images in the `/public/images/` directory
    - Use absolute links regardless of where the markdown file is, i.e.
        - `![some image alt-text](/images/cool-image.png)`
    - Do NOT use relative URIs, e.g.
        - `![some image alt-text](../../images/cool-image.png)`
        - 
 
 
 
Tick off when formatting is completed

- [x] │   │   ├── developers
- [x] │   │   │   ├── dapp-developer
- [x] │   │   │   │   ├── custom-tracer.md            
- [x] │   │   │   │   ├── mobile.md                   
- [x] │   │   │   │   ├── native-accounts.md         
- [x] │   │   │   │   ├── native-bindings.md         
- [x] │   │   │   │   ├── native.md                 
- [x] │   │   │   │   ├── tracers.md                   
- [x] │   │   │   │   └── built-in-tracers.md        
- [x] │   │   │   └── geth-developer               
- [x] │   │   │       ├── code-review-guidelines.md     
- [x] │   │   │       ├── contributing.md            
- [x] │   │   │       ├── devguide.md
- [x] │   │   │       ├── dev-mode.md 
- [x] │   │   │       ├── dns-discovery-setup.md
- [x] │   │   │       ├── issue-handling-workflow.md
- [x] │   │   │       ├── private-network.md         
- [x] │   │   │       └── vulnerabilities.md
- [x] │   │   ├── faq.md
- [x] │   │   ├── fundamentals
- [x] │   │   │   ├── Backup--restore.md             
- [x] │   │   │   ├── Command-Line-Options.md                               
- [x] │   │   │   ├── les.md                         
- [x] │   │   │   ├── account-management.md          
- [x] │   │   │   ├── node-architecture.md           
- [x] │   │   │   ├── security.md                   
- [x] │   │   │   ├── peer-to-peer.md
- [x] │   │   │   ├── mining.md        
- [x] │   │   │   ├── pruning.md
- [x] │   │   │   ├── sync-modes.md                   
- [x] │   │   ├── getting_started
- [x] │   │   │   ├── consensus-clients.md           
- [x] │   │   │   ├── getting-started-with-clef.md  
- [x] │   │   │   └── getting-started.md            
- [x] │   │   │   └── Installing-Geth.md            
- [x] │   │   ├── interacting_with_geth
- [x] │   │   │   ├── JavaScript-Console.md          
- [x] │   │   │   └── RPC
- [x] │   │   │       ├── batch.md
- [x] │   │   │       ├── graphql.md
- [x] │   │   │       ├── ns-admin.md
- [x] │   │   │       ├── ns-clique.md
- [x] │   │   │       ├── ns-debug.md
- [x] │   │   │       ├── ns-eth.md
- [x] │   │   │       ├── ns-les.md
- [x] │   │   │       ├── ns-miner.md
- [x] │   │   │       ├── ns-net.md
- [x] │   │   │       ├── ns-personal.md
- [x] │   │   │       ├── ns-txpool.md
- [x] │   │   │       ├── objects.md
- [x] │   │   │       ├── pubsub.md
- [x] │   │   │       └── server.md
- [x] │   │   ├── monitoring
- [x] │   │   │   ├── dashboards.md                 
- [x] │   │   │   └── metrics.md           
- [x] │   │   └── tools
- [x] │   │       ├── abigen                       
- [x] │   │       ├── Clef
- [x] │   │       │   ├── apis.md
- [x] │   │       │   ├── CliqueSigning.md
- [x] │   │       │   ├── datatypes.md
- [x] │   │       │   ├── Introduction.md         
- [x] │   │       │   ├── Rules.md                 
- [x] │   │       │   ├── Setup.md
- [x] │   │       │   └── Tutorial.md             
- [x] │   │       └── puppeth
- [x] │   │       └── devp2p
- [x] │   └── downloads.md
- [x] │   └── resources.md
- [x] │   └── homepage.md

**Comment by nhsz** [comment]
Closing as this is fixed
