### ISSUE TITLE
Content reviews

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#3]
Tick off pages in list below when they have been reviewed by at least one member of Geth team

- [x] │   │   ├── developers
- [x] │   │   │   ├── dapp-developer
- [x] │   │   │   │   ├── custom-tracer.md        (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   │   ├── mobile.md                   (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   │   ├── native-accounts.md     (reviewed when updated at geth.ethereum.org)    
- [x] │   │   │   │   ├── native-bindings.md      (reviewed when updated at geth.ethereum.org)   
- [x] │   │   │   │   ├── native.md                    (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   │   ├── tracers.md                   (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   │   └── built-in-tracers.md        (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   └── geth-developer               
- [x] │   │   │       ├── code-review-guidelines.md     
- [x] │   │   │       ├── contributing.md            
- [x] │   │   │       ├── devguide.md   (reviewed when updated at geth.ethereum.org)
- [x] │   │   │       ├── dev-mode.md 
- [x] │   │   │       ├── dns-discovery-setup.md
- [x] │   │   │       ├── issue-handling-workflow.md
- [x] │   │   │       ├── private-network.md         (reviewed when updated at geth.ethereum.org)
- [x] │   │   ├── faq.md
- [x] │   │   ├── fundamentals
- [x] │   │   │   ├── Backup--restore.md             
- [x] │   │   │   ├── Command-Line-Options.md     (reviewed when updated at geth.ethereum.org)               
- [x] │   │   │   ├── les.md                                      (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   ├── account-management.md        (reviewed when updated at geth.ethereum.org)  
- [x] │   │   │   ├── node-architecture.md           
- [x] │   │   │   ├── security.md                   
- [x] │   │   │   ├── peer-to-peer.md                      (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   ├── mining.md                      (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   ├── pruning.md         (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   ├── sync-modes.md   (reviewed when updated at geth.ethereum.org)
- [x]  │   │   │   ├── logs.md                    (reviewed when updated at geth.ethereum.org)
- [x] │   │   ├── getting_started
- [x] │   │   │   ├── consensus-clients.md           (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   ├── getting-started-with-clef.md  (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   └── getting-started.md                (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   └── Installing-Geth.md                (reviewed when updated at geth.ethereum.org)
- [x]  │   │   │   └── hardware-requirements.md    (reviewed when updated at geth.ethereum.org)
- [x] │   │   ├── interacting_with_geth
- [x] │   │   │   ├── JavaScript-Console.md          (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   ├── JavaScript-Console_Contracts.md         (reviewed when updated at geth.ethereum.org)
- [x] │   │   │   └── RPC
- [x] │   │   │       ├── batch.md
- [x] │   │   │       ├── graphql.md
- [x] │   │   │       ├── ns-admin.md
- [x] │   │   │       ├── ns-clique.md
- [x] │   │   │       ├── ns-debug.md
- [x] │   │   │       ├── ns-eth.md
- [x] │   │   │       ├── ns-les.md
- [x] │   │   │       ├── ns-miner.md
- [x] │   │   │       ├── ns-net.md
- [x] │   │   │       ├── ns-personal.md
- [x]  │   │   │       ├── ns-personal-deprecation-notes.md   (reviewed when updated at geth.ethereum.org)
- [x] │   │   │       ├── ns-txpool.md
- [x] │   │   │       ├── objects.md
- [x] │   │   │       ├── pubsub.md
- [x] │   │   │       └── server.md                          (reviewed when updated at geth.ethereum.org)
- [x] │   │   ├── monitoring
- [x] │   │   │   ├── dashboards.md      (reviewed when updated at geth.ethereum.org)           
- [x] │   │   │   └── metrics.md           (reviewed when updated at geth.ethereum.org) 
- [x] │   │   │   └── ethstats.md         
- [x] │   │   └── tools
- [x] │   │       ├── abigen                       (reviewed when updated at geth.ethereum.org)
- [x] │   │       ├── Clef
- [x] │   │       │   ├── apis.md                 (reviewed when updated at geth.ethereum.org)
- [x] │   │       │   ├── CliqueSigning.md  (reviewed when updated at geth.ethereum.org)
- [x] │   │       │   ├── datatypes.md       (reviewed when updated at geth.ethereum.org)
- [x] │   │       │   ├── Introduction.md    (reviewed when updated at geth.ethereum.org)         
- [x] │   │       │   ├── Rules.md              (reviewed when updated at geth.ethereum.org)   
- [x] │   │       │   ├── Setup.md             (reviewed when updated at geth.ethereum.org)
- [x] │   │       │   └── Tutorial.md           (reviewed when updated at geth.ethereum.org)   
- [x] │   │       └── puppeth
- [x] │   │       └── devp2p                      (reviewed when updated at geth.ethereum.org)
- [x] │   └── downloads.md
- [x] │   └── resources.md
- [x] │   └── homepage.md

**Comment by MariusVanDerWijden** [comment]
devmode (--dev) lgtm

**Comment by jmcook1186** [comment]
closing - completed and signed off Dec 22
