### ISSUE TITLE
Downloads header overflowing

### ISSUE THREAD

**Issue by corwintines** [ethereum/geth-website#38]
<img width="225" alt="Screen Shot 2022-11-17 at 7 27 33 PM" src="https://user-images.githubusercontent.com/15589226/202602849-58e58f4b-4166-43f7-8de7-c8eb8561d3e1.png">

Downloads header overflowing on mobile view

**Comment by corwintines** [comment]
Happens around <298px. Not sure if this is an issue, just noting in case you have an opinion @nloureiro @nhsz

**Comment by nloureiro** [comment]
> Happens around <298px. Not sure if this is an issue, just noting in case you have an opinion @nloureiro @nhsz

we don't support screen sizes below 320px. that's the minimum recommended even for old smartphones.

**Comment by wackerow** [comment]
I'm seeing it happen wider than that... This is 320px wide:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/54227730/202913992-85f1c1e6-3b9f-49b8-bb30-587002239fe1.png">

If we add a width of 100% as a base case for the `GopherDownloads` component, and remove the x-padding on its container, this resolves to:

<img width="320" alt="image" src="https://user-images.githubusercontent.com/54227730/202914337-df81b773-9876-4298-9992-a8ef25f8b1ec.png">

I would recommend we do that. I'll put up a PR with those adjustments
