### ISSUE TITLE
downloads table expand button returns nonsense values in text

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#42]
## Description

Clicking "show older entries" on the tables on the downloads page expands the table but also returns the following text in the table's footer:

"Showing 20 latest releases of a total 12 releases"

You can't be showing 20 out of 12, so I assume the logic is screwed up somewhere.

Also, clicking the button again does not change the table layout, but does increase the numerator by ten each time, so the text updates e.g.:

click -> "Showing 20 latest releases of a total 12 releases" 
click -> "Showing 30 latest releases of a total 12 releases" 
click -> "Showing 40 latest releases of a total 12 releases" 

This applies to both tables.

**Comment by nhsz** [comment]
closing as this is not a but, hardcoded data will be replaced with real data after https://github.com/ethereum/geth-website/pull/46 is merged.
