### ISSUE TITLE
Ideas for new pages

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#5]
These are pages not currently included on the website but might be nice to add after the new site is live: 

- [x] geth system requirements
- [x] consensus clients
- [x] node architecture
- [x] security best practice
- [x] devp2p
- [x] pruning
- [x] ethstats
- [x] updated FAQs
- [x] understanding log messages
- [x] additional cmd tool docs
- [x] sync modes
- [x] break out tracing into new pages, + info on override etc
- [x] javascript console with contracts
- [x] puppeth
- [x] abigen

**Comment by samajammin** [comment]
A couple more ideas for pages (which I'd love input on!):
- Contributing page: https://www.notion.so/efdn/Propose-contribute-page-5835b3b1fdc84f6f91b659b58bc48719
- Bug bounty page: https://www.notion.so/efdn/Propose-bug-bounty-page-2e8e595c20b34d599e9a5ca72a47e757

**Comment by jmcook1186** [comment]
closing - the pages we wanted have been added to the new website.
