### ISSUE TITLE
[DESGIN BUG] Change the background color for the code snippets

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#52]
![Screen Shot 2022-11-25 05 34 06 PM](https://user-images.githubusercontent.com/1120748/204034045-67e08188-2fc2-44f4-9646-0466ba21c6bd.png)

**Comment by wackerow** [comment]
Updating the code background color in light mode has not yet been fixed, but there is a PR up to fix it: #55

**Comment by wackerow** [comment]
Shoot, my bad... got the screenshot mixed up, and see the source of truth is to use `gray.200`, my bad, closing back out
