### ISSUE TITLE
[DESIGN BIG] responsive behaviour

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#53]
weird responsive behaviour

Is there a reason?

![Screen Shot 2022-11-25 05 38 20 PM](https://user-images.githubusercontent.com/1120748/204034430-da0cf3e7-88a2-4cbc-887b-f13d8ebf1de9.png)

**Comment by ai-slave** [comment]
My take is that this is normal since you want not more than 10 words on avg in one line to keep text readable.

**Comment by nloureiro** [comment]
> My take is that this is normal since you want not more than 10 words on avg in one line to keep text readable.

Not sure I follow, but a responsive behavior should adopt the entire width of the website to the screen dimensions. In this case, the website below a certain breakpoint jumps to a fixed small size and doesn't take whole screen advantage of real estate. This increases the vertical scrolling of the website and therefor degrades the experience.

**Comment by ai-slave** [comment]
I was talking about this, that basically that's the max width for the content. https://baymard.com/blog/line-length-readability
But we can put something on the side

**Comment by nloureiro** [comment]
> I was talking about this, that basically that's the max width for the content. https://baymard.com/blog/line-length-readability
> But we can put something on the side

I'm aware of the limit per line, and to be fair, if we want to be strict on this, we should restrict the size to a bigger break point.

My point is more to avoid the content jumping on a specific breakpoint. This will look weird on bigger smartphones and small tablets with extra margins on the side.

https://user-images.githubusercontent.com/1120748/204340761-92645f55-2024-4109-b918-3002d38eb8de.mov

**Comment by wackerow** [comment]
@nhsz Easy fix, I can patch this right now
