### ISSUE TITLE
[DESIGN UPDATE] notes box render in html

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#69]
On the current website, there is a note box on the dev docs that render like this
![Screen Shot 2022-11-30 10 31 27 AM](https://user-images.githubusercontent.com/1120748/204773100-604a1926-cd5f-4952-8ed1-82a75cd8ddc9.png)

**Comment by corwintines** [comment]
@nloureiro I was basing off https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=1419%3A16364 let me know which is the right one

**Comment by nloureiro** [comment]
> @nloureiro I was basing off https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=1419%3A16364 let me know which is the right one

yes. use this design.

**Comment by wackerow** [comment]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/54227730/205212299-feedfd7c-af29-45b5-ab42-29c7ead3af8c.png">

This appears to be fixed with PR #40
@nloureiro Please fell free to re-open if I'm missing something
