### ISSUE TITLE
[DESIGN BUG] Left navigation extra pixel

### ISSUE THREAD

**Issue by nloureiro** [ethereum/geth-website#72]
![Screen Shot 2022-11-30 11 21 01 AM](https://user-images.githubusercontent.com/1120748/204783398-383ef7a4-623c-449e-a85d-225aad2159b7.png)

there is an extra pixel border in the left navigation, button border I guess.

**Comment by wackerow** [comment]
<img width="360" alt="image" src="https://user-images.githubusercontent.com/54227730/205216698-e2a8de72-85f6-4125-8146-a457fe34327c.png">

This has since been fixed, closing out. Feel free to reopen if I'm missing anything.
