### ISSUE TITLE
Menu broken on tablet

### ISSUE THREAD

**Issue by konopkja** [ethereum/geth-website#79]
<img width="820" alt="Screenshot 2022-12-01 at 14 45 15" src="https://user-images.githubusercontent.com/100724231/205020402-b246f45a-3a11-4e5d-af09-6b8f29b1f887.png">

**Comment by minimalsm** [comment]
@konopkja I'm not able to reproduce this. What device/browser/resolution was this on?

**Comment by konopkja** [comment]
latest chrome, on my  14" macbook when i resize it to half screen.

**Comment by konopkja** [comment]
https://user-images.githubusercontent.com/100724231/205055590-03345ea2-319a-45c4-b64b-11317b5ab4e1.mov
