### ISSUE TITLE
[UI bug] - Too much spacing between markdowns sections on developer docs

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#83]
- The spacing between sections of the developer docs is too large. 
- [The Figma file specifies 64px between the final element and the next H2](https://www.figma.com/file/ekzIgwyeVKLtFSAcnA0Q0D/geth-website?node-id=1578%3A19042&t=IM0cQlwLjB4YYIVG-1)
- We've got 92px margin between last paragraph and start of the next heading (28px bottom + 64px top). 

These margins should collapse:

![image](https://user-images.githubusercontent.com/62268199/205050302-5b31cf82-42bd-4054-9dba-cc0a8cda5f74.png)

![image](https://user-images.githubusercontent.com/62268199/205050349-e5f67679-4a18-47c0-a484-6b335e60cc9c.png)

![image](https://user-images.githubusercontent.com/62268199/205050475-c8ab3812-5f39-4c55-a74c-8f2e40a0cc6e.png)

This is especially pronounced on mobile: 

![image](https://user-images.githubusercontent.com/62268199/205050734-cfee34e1-eb31-438e-8cd8-d27a3b3d4b2c.png)

**Comment by nloureiro** [comment]
The <p> tag still has the default margins on the :first-child and :last-child which makes the spacing bigger 

See if this screech helps
![Screen Shot 2022-12-02 09 53 19 AM](https://user-images.githubusercontent.com/1120748/205265804-fa7a60de-6fff-40d8-9e22-f52e9f6caaca.png)
