### ISSUE TITLE
[Logic bug] - Last edited timestamp is incorrect

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#88]
- Last edited logic appears to be incorrect. It's showing every page as last edited today. 
- I'd expect it to show when the page itself was last edited.

![image](https://user-images.githubusercontent.com/62268199/205052309-0d74dd8d-d131-4851-8838-71b78e724d2d.png)

**Comment by wackerow** [comment]
I believe it's currently being pulled using `fs`, while we may need to use a GitHub API request
