### ISSUE TITLE
[UI/UX bug] - Footer buttons are only partially clickable

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#90]
- The entire button link should be clickable in the footer
- This bug is not present in top nav / other button links on page

![331ba0372d08fd08d1724df283cd846c (1)](https://user-images.githubusercontent.com/62268199/205052603-3d9a1ef9-07fd-4852-a14d-ecd528e8d78f.gif)

**Comment by corwintines** [comment]
@nhsz made a fix for this
