### ISSUE TITLE
[UI bug] - Overflow on developer docs with long code blocks

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#92]
On mobile: long code blocks cause a horizontal scroll

![231047e020171514382d7f9644b8de1f](https://user-images.githubusercontent.com/62268199/205053624-3d2a4978-1ded-4524-9ab3-aba0c4519889.gif)

**Comment by corwintines** [comment]
@wackerow brought this up this morning, but I think this is fixed. I tested on my iPhone and this isnt a problem anymore. Going to close this out, but if you run into it again just reopen this.
