### ISSUE TITLE
[UI bug] - Developer docs: No margin between content and table of contents

### ISSUE THREAD

**Issue by minimalsm** [ethereum/geth-website#95]
On the developer docs, there is no margin between content and table of contents.

This is leading to horizontal scroll in some cases.

<img width="941" alt="Screenshot 2022-12-01 at 13 08 18" src="https://user-images.githubusercontent.com/62268199/205060813-69750735-0cd2-42f9-95de-4c3042cc5cd9.png">

**Comment by nloureiro** [comment]
you are using ` --chakra-space-8: 2rem;` on left side, add the same on the right side
![Screen Shot 2022-12-02 10 54 10 AM](https://user-images.githubusercontent.com/1120748/205277367-049ba6b1-1f02-456e-b5ee-fa7f593691cd.png)

**Comment by wackerow** [comment]
Fixed with #110, closing for now
