### ISSUE TITLE
[docs] LHS menu should be closed by default

### ISSUE THREAD

**Issue by jmcook1186** [ethereum/geth-website#97]
By default the navigation menu on the left-hand side is expanded - I think this creates a bit of friction for the user - suggest making the menu closed by default and only opened on-click.

![image](https://user-images.githubusercontent.com/33655003/205066955-28d16695-1db9-4cdc-bd49-c5c8198379a1.png)

**Comment by nloureiro** [comment]
I agree with @jmcook1186 that all menu open is not good.

either all closed or open the first chapter > Getting started

**Comment by corwintines** [comment]
@nhsz pushed up a PR for this
